// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'blur': string;
  'controlsContainer': string;
  'definition': string;
  'definitionsContainer': string;
  'example': string;
  'leftArrowContainer': string;
  'rightArrowContainer': string;
  'textContainer': string;
}
export const cssExports: CssExports;
export default cssExports;
