// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'defFrame': string;
  'frame': string;
  'nullFrame': string;
}
export const cssExports: CssExports;
export default cssExports;
