// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'disabledArrowContainer': string;
  'downArrowContainer': string;
  'typesContainer': string;
  'typesLabel': string;
  'upArrowContainer': string;
}
export const cssExports: CssExports;
export default cssExports;
